[mypy]
python_version = 3.12
strict = True
follow_imports = normal
warn_unreachable = True
no_implicit_reexport = True
exclude = venv

# Если не хотите возиться со стабами asyncpg, раскомментируйте:
# [mypy-asyncpg.*]
# ignore_missing_imports = True