// packages/aoa-client-js/src/codegen/check-drift.test.ts
import { afterEach, describe, expect, it, vi } from "vitest";

import { diffGeneratedSource } from "./check-drift.ts";
import { generateClient } from "./generate-client.ts";

const HEADER = (url: string, version: string) =>
  `// AUTO-GENERATED by aoa-client-js/codegen — DO NOT EDIT BY HAND.\n// Source: ${url}\n// Manifest version: ${version}`;

describe("diffGeneratedSource -- synthetic fixtures", () => {
  it("returns null for identical sources", () => {
    const source = `${HEADER("https://a", "sha256:x")}\n\nexport interface FooParams {\n  x: number;\n}`;
    expect(diffGeneratedSource(source, source)).toBeNull();
  });

  it("returns null when only the environment-dependent Source: line differs", () => {
    const committed = `${HEADER("https://staging", "sha256:x")}\n\nexport interface FooParams {\n  x: number;\n}`;
    const fresh = `${HEADER("http://localhost:8000", "sha256:x")}\n\nexport interface FooParams {\n  x: number;\n}`;
    expect(diffGeneratedSource(committed, fresh)).toBeNull();
  });

  it("reports (missing) when the committed side has no Manifest version: line at all", () => {
    const committed = `// some other comment\n\nexport interface FooParams {\n  x: number;\n}`;
    const fresh = `${HEADER("https://a", "sha256:new")}\n\nexport interface FooParams {\n  x: number;\n}`;
    expect(diffGeneratedSource(committed, fresh)).toContain("manifest_version: (missing) -> sha256:new");
  });

  it("reports (missing) when the fresh side has no Manifest version: line at all", () => {
    const committed = `${HEADER("https://a", "sha256:old")}\n\nexport interface FooParams {\n  x: number;\n}`;
    const fresh = `// some other comment\n\nexport interface FooParams {\n  x: number;\n}`;
    expect(diffGeneratedSource(committed, fresh)).toContain("manifest_version: sha256:old -> (missing)");
  });

  it("treats a source with no blank line anywhere as having no header to strip", () => {
    const committed = "export interface FooParams {\n  x: number;\n}";
    const fresh = "export interface FooParams {\n  y: number;\n}";
    expect(diffGeneratedSource(committed, fresh)).toContain("changed (same name, different shape -- schema drift): FooParams");
  });

  it("reports a manifest_version change", () => {
    const committed = `${HEADER("https://a", "sha256:old")}\n\nexport interface FooParams {\n  x: number;\n}`;
    const fresh = `${HEADER("https://a", "sha256:new")}\n\nexport interface FooParams {\n  x: number;\n}`;
    expect(diffGeneratedSource(committed, fresh)).toContain("manifest_version: sha256:old -> sha256:new");
  });

  it("reports a changed interface by name when its shape differs (a renamed params field)", () => {
    const committed = `${HEADER("https://a", "sha256:x")}\n\nexport interface CancelOrderParams {\n  order_id: number;\n}`;
    const fresh = `${HEADER("https://a", "sha256:x")}\n\nexport interface CancelOrderParams {\n  orderId: number;\n}`;
    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).toContain("changed (same name, different shape -- schema drift): CancelOrderParams");
  });

  it("reports a missing declaration when an endpoint was added to the live manifest", () => {
    const committed = `${HEADER("https://a", "sha256:x")}\n\nexport interface FooParams {\n  x: number;\n}`;
    const fresh = `${HEADER("https://a", "sha256:x")}\n\nexport interface FooParams {\n  x: number;\n}\n\nexport interface BarParams {\n  y: string;\n}`;
    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).toContain("missing (in the live manifest, not in the committed file): BarParams");
  });

  it("reports a stale declaration when an endpoint was removed from the live manifest", () => {
    const committed = `${HEADER("https://a", "sha256:x")}\n\nexport interface FooParams {\n  x: number;\n}\n\nexport interface BarParams {\n  y: string;\n}`;
    const fresh = `${HEADER("https://a", "sha256:x")}\n\nexport interface FooParams {\n  x: number;\n}`;
    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).toContain("stale (in the committed file, not in the live manifest -- endpoint removed?): BarParams");
  });

  it("collapses multiple joined descriptor consts into one '(endpoint descriptors)' unit rather than misnaming by the first one", () => {
    const committed = `${HEADER("https://a", "sha256:x")}\n\nconst FOO_DESCRIPTOR = { method: "GET", path: "/foo" };\nconst BAR_DESCRIPTOR = { method: "GET", path: "/bar" };`;
    const fresh = `${HEADER("https://a", "sha256:x")}\n\nconst FOO_DESCRIPTOR = { method: "GET", path: "/foo" };\nconst BAR_DESCRIPTOR = { method: "POST", path: "/bar" };`;
    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).toContain("changed (same name, different shape -- schema drift): (endpoint descriptors)");
  });

  // Audit finding 15: a pure route/method rename (no schema change) only ever reported
  // as the whole "(endpoint descriptors)" block changing, with no way to tell which of
  // several endpoints actually moved without diffing the block by hand.
  it("names the specific descriptor whose route changed, on top of the block-level report", () => {
    const committed = `${HEADER("https://a", "sha256:x")}\n\nconst FOO_DESCRIPTOR = { method: "GET", path: "/foo" };\nconst BAR_DESCRIPTOR = { method: "GET", path: "/bar" };`;
    const fresh = `${HEADER("https://a", "sha256:x")}\n\nconst FOO_DESCRIPTOR = { method: "GET", path: "/foo" };\nconst BAR_DESCRIPTOR = { method: "GET", path: "/bar-renamed" };`;
    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).toContain("changed (same name, different shape -- schema drift): (endpoint descriptors)");
    expect(drift).toContain("within (endpoint descriptors), route changed for: BAR_DESCRIPTOR");
    expect(drift).not.toContain("FOO_DESCRIPTOR");
  });

  it("names every descriptor whose route changed when more than one moves at once", () => {
    const committed = `${HEADER("https://a", "sha256:x")}\n\nconst FOO_DESCRIPTOR = { method: "GET", path: "/foo" };\nconst BAR_DESCRIPTOR = { method: "GET", path: "/bar" };`;
    const fresh = `${HEADER("https://a", "sha256:x")}\n\nconst FOO_DESCRIPTOR = { method: "POST", path: "/foo" };\nconst BAR_DESCRIPTOR = { method: "GET", path: "/bar-renamed" };`;
    const drift = diffGeneratedSource(committed, fresh);
    const detailLine = drift!.split("\n").find((line) => line.includes("route changed for"));
    expect(detailLine).toContain("FOO_DESCRIPTOR");
    expect(detailLine).toContain("BAR_DESCRIPTOR");
  });

  it("adds no misleading 'route changed' detail when the block changed only because a new endpoint was added", () => {
    const committed = `${HEADER("https://a", "sha256:x")}\n\nconst FOO_DESCRIPTOR = { method: "GET", path: "/foo" };`;
    const fresh = `${HEADER("https://a", "sha256:x")}\n\nconst FOO_DESCRIPTOR = { method: "GET", path: "/foo" };\nconst BAR_DESCRIPTOR = { method: "GET", path: "/bar" };`;
    const drift = diffGeneratedSource(committed, fresh);
    // The block as a whole did change (one more line) -- but FOO's own line didn't, and
    // there's no "committed" BAR line to compare against, so there's nothing to name as
    // having "moved". diffDescriptorRoutes must not report an empty/misleading detail.
    expect(drift).toContain("changed (same name, different shape -- schema drift): (endpoint descriptors)");
    expect(drift).not.toContain("route changed for");
  });

  // Audit finding 17: the imports/re-exports block (always the file's first content
  // block) never matched DECLARATION_NAME_PATTERN -- neither a bare `import` line nor
  // `export type { X } from "..."` (no `= ...` after the name) fits `export
  // (interface|type|function|const) NAME`. It fell through to the generic, useless
  // "(unrecognized block 0)".
  it("names the imports block '(imports)' instead of '(unrecognized block 0)'", () => {
    const committed = `${HEADER("https://a", "sha256:x")}\n\nimport { z } from "zod";\nimport { makeGatePrimitive } from "aoa-client-js";\n\nexport interface FooParams {\n  x: number;\n}`;
    const fresh = `${HEADER("https://a", "sha256:x")}\n\nimport { z } from "zod";\nimport { makeGatePrimitive, extra } from "aoa-client-js";\n\nexport interface FooParams {\n  x: number;\n}`;
    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).toContain("changed (same name, different shape -- schema drift): (imports)");
    expect(drift).not.toContain("unrecognized block");
  });

  it("still falls back to '(unrecognized block N)' for a block that is neither a descriptor, imports, nor a matched declaration", () => {
    const committed = `${HEADER("https://a", "sha256:x")}\n\n// a stray top-level comment block, not a declaration`;
    const fresh = `${HEADER("https://a", "sha256:x")}\n\n// a DIFFERENT stray top-level comment block`;
    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).toContain("changed (same name, different shape -- schema drift): (unrecognized block 0)");
  });
});

describe("diffGeneratedSource -- against real generateClient output", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  function stubFetchJson(body: unknown): void {
    vi.stubGlobal(
      "fetch",
      vi.fn(async () => ({ ok: true, status: 200, statusText: "OK", json: async () => body })),
    );
  }

  const RESOLVE_RESPONSE_SCHEMA_ENTRY = {
    mode: "serialization",
    json_schema: {
      $defs: { BaseVerdict: { properties: { kind: { type: "string" } }, type: "object" } },
      properties: { version: { type: "integer" }, results: { items: { $ref: "#/$defs/BaseVerdict" }, type: "array" } },
      required: ["version", "results"],
      type: "object",
    },
  };

  function manifestWithParamField(fieldName: string) {
    return {
      manifest_version: `sha256:${fieldName}`,
      version: 1,
      manifest_schema_version: 2,
      endpoints: [
        {
          operation: "POST /actions/cancel-order",
          name: "CancelOrderAction",
          domain: "OrdersDomain",
          description: "x",
          route: { method: "POST", path: "/actions/cancel-order" },
          params_schema: { type: "object", properties: { [fieldName]: { type: "integer" } }, required: [fieldName] },
          result_schema: { type: "object", properties: { status: { type: "string" } }, required: ["status"] },
        },
      ],
      schemas: { ResolveResponse: RESOLVE_RESPONSE_SCHEMA_ENTRY },
    };
  }

  it("detects real drift end to end: a renamed params field in the live manifest shows up as a changed CancelOrderParams", async () => {
    stubFetchJson(manifestWithParamField("order_id"));
    const committed = await generateClient("https://x/client-manifest.json");

    stubFetchJson(manifestWithParamField("orderId"));
    const fresh = await generateClient("https://x/client-manifest.json");

    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).toContain("manifest_version:");
    expect(drift).toContain("changed (same name, different shape -- schema drift): CancelOrderParams");
  });

  it("reports null for two real generateClient calls against the identical manifest", async () => {
    stubFetchJson(manifestWithParamField("order_id"));
    const first = await generateClient("https://x/client-manifest.json");
    stubFetchJson(manifestWithParamField("order_id"));
    const second = await generateClient("https://x/client-manifest.json");
    expect(diffGeneratedSource(first, second)).toBeNull();
  });

  // Audit finding 17, end to end: confirms the real, current generateClient() output's
  // imports block actually has the shape check-drift.ts's fix relies on (starts with a
  // bare `import`, not `export`) -- not just a hand-constructed fixture shaped to match.
  it("the real generated file's imports block starts with a bare import, matching the fix's detection", async () => {
    stubFetchJson(manifestWithParamField("order_id"));
    const source = await generateClient("https://x/client-manifest.json");
    const importsBlock = source.split(/\n{2,}/)[1];
    expect(importsBlock?.startsWith("import ")).toBe(true);
  });

  function manifestWithTwoRoutes(cancelOrderPath: string) {
    return {
      manifest_version: `sha256:${cancelOrderPath}`,
      version: 1,
      manifest_schema_version: 2,
      endpoints: [
        {
          operation: `POST ${cancelOrderPath}`,
          name: "CancelOrderAction",
          domain: "OrdersDomain",
          description: "x",
          route: { method: "POST", path: cancelOrderPath },
          params_schema: { type: "object", properties: { order_id: { type: "integer" } }, required: ["order_id"] },
          result_schema: { type: "object", properties: { status: { type: "string" } }, required: ["status"] },
        },
        {
          operation: "GET /actions/ping",
          name: "PingAction",
          domain: "SystemDomain",
          description: "x",
          route: { method: "GET", path: "/actions/ping" },
          params_schema: { type: "object", properties: {} },
          result_schema: { type: "object", properties: { message: { type: "string" } }, required: ["message"] },
        },
      ],
      schemas: { ResolveResponse: RESOLVE_RESPONSE_SCHEMA_ENTRY },
    };
  }

  // Audit finding 15, end to end: a real route rename (path only, schema untouched)
  // through a real generateClient() call.
  it("detects a real pure route rename end to end and names the specific moved endpoint (audit finding 15)", async () => {
    stubFetchJson(manifestWithTwoRoutes("/actions/cancel-order"));
    const committed = await generateClient("https://x/client-manifest.json");

    stubFetchJson(manifestWithTwoRoutes("/actions/cancel-order-v2"));
    const fresh = await generateClient("https://x/client-manifest.json");

    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).not.toBeNull();
    expect(drift).toContain("within (endpoint descriptors), route changed for: CANCEL_ORDER_DESCRIPTOR");
    // PingAction's own route never changed -- it must not show up in the detail line.
    expect(drift).not.toContain("PING_DESCRIPTOR");
  });

  // Audit finding 2's original symptom: --check silently reported "up to date" for a
  // real required-field rename, because the renamed field lived in a $defs entry
  // hoisted under a name that collided textually with an unrelated endpoint's own
  // top-level name -- the second block silently overwrote the first in
  // splitDeclarations's Map, on BOTH the committed and fresh sides, so the comparison
  // never actually reached the changed content. Fixed at the source (naming.ts's
  // NameRegistry now spans hoisted names too, see generate-client.test.ts), which this
  // re-verifies from check-drift's own point of view: the two names no longer collide,
  // so the field rename is visible again.
  function manifestWithCollidingNames(nestedFieldName: string) {
    return {
      manifest_version: `sha256:${nestedFieldName}`,
      version: 1,
      manifest_schema_version: 2,
      endpoints: [
        {
          operation: "POST /a",
          name: "AAction",
          domain: "TestDomain",
          description: "x",
          route: { method: "POST", path: "/a" },
          params_schema: { type: "object", properties: {} },
          result_schema: {
            $defs: { XParams: { type: "object", properties: { [nestedFieldName]: { type: "string" } }, required: [nestedFieldName] } },
            type: "object",
            properties: { x_ref: { $ref: "#/$defs/XParams" } },
            required: ["x_ref"],
          },
        },
        {
          operation: "POST /a-result-x",
          name: "AResultXAction",
          domain: "TestDomain",
          description: "y",
          route: { method: "POST", path: "/a-result-x" },
          params_schema: { type: "object", properties: { own_field: { type: "boolean" } }, required: ["own_field"] },
          result_schema: { type: "object", properties: {} },
        },
      ],
      schemas: { ResolveResponse: RESOLVE_RESPONSE_SCHEMA_ENTRY },
    };
  }

  it("detects a required field renamed inside a hoisted $defs entry, even when an unrelated endpoint's own name would otherwise collide with it", async () => {
    stubFetchJson(manifestWithCollidingNames("z"));
    const committed = await generateClient("https://x/client-manifest.json");

    stubFetchJson(manifestWithCollidingNames("zed"));
    const fresh = await generateClient("https://x/client-manifest.json");

    const drift = diffGeneratedSource(committed, fresh);
    expect(drift).not.toBeNull();
    expect(drift).toContain("changed (same name, different shape -- schema drift): AResultXParams");
  });
});
