// packages/aoa-client-js/src/codegen/generate-client.ts
//
// generateClient(url) — the static codegen entry point (chapter 5, task 1). Fetches
// GET /client-manifest.json and returns a self-contained TypeScript source string: one
// Params/Result interface pair per endpoint, plus the wire-contract zod validator
// ResolveResponseSchema. The three Verdict outcome types are re-exported from the
// runtime package rather than redeclared here — the manifest's own BaseVerdict entry is
// deliberately abstract (kind only, see json-schema-to-zod.ts), so there is no schema
// data to mechanically regenerate FailSecurityVerdict/FailErrorVerdict's `reason` field
// from, and redeclaring a second, hand-maintained copy would be exactly the kind of
// dual-source-of-truth this whole chapter exists to avoid.
//
// Laying endpoint objects out into `api` (the hybrid path/dot-alias rule, GateApi vs.
// CallableApi) is a separate task — this function does not build `api` yet.

import { assertManifestShape, type Manifest, type ManifestEndpoint } from "./manifest-types.ts";
import { parseRootSchema } from "./json-schema-ir.ts";
import { renderParamsOrResultInterface } from "./json-schema-to-ts.ts";
import { renderResolveResponseZodSchema } from "./json-schema-to-zod.ts";
import { NameRegistry, deriveEndpointBaseName } from "./naming.ts";

export async function generateClient(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch manifest from ${url}: HTTP ${res.status} ${res.statusText}`);
  }
  const body: unknown = await res.json();
  assertManifestShape(body, url);
  return renderClientSource(body, url);
}

function renderClientSource(manifest: Manifest, url: string): string {
  const registry = new NameRegistry();
  const endpointBlocks = manifest.endpoints.map((endpoint) => renderEndpointTypes(endpoint, registry));

  const resolveResponseEntry = manifest.schemas.ResolveResponse;
  if (!resolveResponseEntry) {
    throw new Error(`Manifest fetched from ${url} is missing the required "schemas.ResolveResponse" entry`);
  }
  const parsedResolveResponse = parseRootSchema(resolveResponseEntry.json_schema, "schemas.ResolveResponse");
  const zodBlock = [
    '// Wire contract validator — generated from the manifest\'s "schemas.ResolveResponse" entry.',
    renderResolveResponseZodSchema(parsedResolveResponse),
  ].join("\n");

  const sections = [renderHeader(url, manifest), renderImports(), ...endpointBlocks, zodBlock];
  return `${sections.join("\n\n")}\n`;
}

function renderEndpointTypes(endpoint: ManifestEndpoint, registry: NameRegistry): string {
  const base = registry.claimBase(deriveEndpointBaseName(endpoint.name), endpoint.operation);
  const paramsName = `${base}Params`;
  const resultName = `${base}Result`;

  const parsedParams = parseRootSchema(endpoint.params_schema, `${endpoint.operation} params_schema`);
  const parsedResult = parseRootSchema(endpoint.result_schema, `${endpoint.operation} result_schema`);

  const paramsSource = renderParamsOrResultInterface(paramsName, parsedParams, (ref) => `${paramsName}${ref}`);
  const resultSource = renderParamsOrResultInterface(resultName, parsedResult, (ref) => `${resultName}${ref}`);

  return [`// ${endpoint.operation}`, paramsSource, "", resultSource].join("\n");
}

function renderHeader(url: string, manifest: Manifest): string {
  return [
    "// AUTO-GENERATED by aoa-client-js/codegen — DO NOT EDIT BY HAND.",
    `// Source: ${url}`,
    `// Manifest version: ${manifest.manifest_version}`,
  ].join("\n");
}

function renderImports(): string {
  return [
    'import { z } from "zod";',
    'export type { AllowedVerdict, FailErrorVerdict, FailSecurityVerdict, Verdict } from "aoa-client-js";',
  ].join("\n");
}
