// packages/aoa-client-js/src/codegen/generate-client.ts
//
// Fetches the server's published list of actions and returns a complete TypeScript file
// as text: a parameter and result type per action, the api object over them, and the
// validator for what the server sends back. The three answer types are re-exported from
// the runtime package instead of being regenerated -- the published schema for them
// carries only the name, so there is nothing to generate a `reason` field from -- and
// writing a second copy by hand is exactly the duplication this generator exists to
// remove.

import { assertManifestShape, type Manifest, type ManifestEndpoint } from "../manifest-types.ts";
import { parseRootSchema } from "./json-schema-ir.ts";
import { renderParamsOrResultInterface } from "./json-schema-to-ts.ts";
import { renderResolveResponseZodSchema } from "./json-schema-to-zod.ts";
import { NameRegistry, assertValidBaseName, deriveEndpointBaseName } from "./naming.ts";
import { renderApiLayout } from "./api-layout-to-ts.ts";
import { buildLayout, type LayoutEndpoint } from "../path-layout.ts";

export async function generateClient(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch manifest from ${url}: HTTP ${res.status} ${res.statusText}`);
  }
  const body: unknown = await res.json();
  assertManifestShape(body, url);
  return renderClientSource(body, url);
}

function renderClientSource(manifest: Manifest, url: string): string {
  const registry = new NameRegistry();
  const rendered = manifest.endpoints.map((endpoint) => renderEndpointTypes(endpoint, registry));
  const endpointBlocks = rendered.map((r) => r.source);
  const layoutEndpoints: LayoutEndpoint[] = rendered.map((r) => r.layoutEndpoint);

  const { typesSource, factoriesSource } = renderApiLayout(buildLayout(layoutEndpoints));

  const resolveResponseEntry = manifest.schemas.ResolveResponse;
  if (!resolveResponseEntry) {
    throw new Error(`Manifest fetched from ${url} is missing the required "schemas.ResolveResponse" entry`);
  }
  const parsedResolveResponse = parseRootSchema(resolveResponseEntry.json_schema, "schemas.ResolveResponse");
  const zodBlock = [
    '// Wire contract validator — generated from the manifest\'s "schemas.ResolveResponse" entry.',
    renderResolveResponseZodSchema(parsedResolveResponse),
  ].join("\n");

  const sections = [renderHeader(url, manifest), renderImports(), ...endpointBlocks, typesSource, factoriesSource, zodBlock];
  return `${sections.join("\n\n")}\n`;
}

function renderEndpointTypes(endpoint: ManifestEndpoint, registry: NameRegistry): { source: string; layoutEndpoint: LayoutEndpoint } {
  const rawBase = deriveEndpointBaseName(endpoint.name);
  // Refuse an unusable name before the registry ever sees it. Adding a number resolves a
  // clash between two otherwise valid names; it cannot repair a name that was never valid,
  // and would turn an empty one into "2".
  assertValidBaseName(rawBase, endpoint);
  const base = registry.claimBase(rawBase, endpoint.operation);
  const paramsName = `${base}Params`;
  const resultName = `${base}Result`;

  const parsedParams = parseRootSchema(endpoint.params_schema, `${endpoint.operation} params_schema`);
  const parsedResult = parseRootSchema(endpoint.result_schema, `${endpoint.operation} result_schema`);

  // A name lifted out of a nested definition is built by gluing strings together and is
  // unique by luck. Claiming it from the same registry as everything else makes the clash
  // impossible instead of silent: TypeScript merges two interfaces sharing a name rather
  // than complaining. Idempotent for the same pair, so re-hoisting the same reference
  // twice within one endpoint's own interface still resolves to the same name.
  const paramsSource = renderParamsOrResultInterface(paramsName, parsedParams, (ref) =>
    registry.claimName(`${paramsName}${ref}`, endpoint.operation),
  );
  const resultSource = renderParamsOrResultInterface(resultName, parsedResult, (ref) =>
    registry.claimName(`${resultName}${ref}`, endpoint.operation),
  );

  return {
    source: [`// ${endpoint.operation}`, paramsSource, "", resultSource].join("\n"),
    layoutEndpoint: { operation: endpoint.operation, method: endpoint.route.method, path: endpoint.route.path, baseName: base },
  };
}

function renderHeader(url: string, manifest: Manifest): string {
  return [
    "// AUTO-GENERATED by aoa-client-js/codegen — DO NOT EDIT BY HAND.",
    `// Source: ${url}`,
    `// Manifest version: ${manifest.manifest_version}`,
  ].join("\n");
}

function renderImports(): string {
  return [
    'import { z } from "zod";',
    'import { makeCallablePrimitive, makeGatePrimitive } from "aoa-client-js";',
    'import type { ActionInvoker, CallablePrimitive, GatePrimitive, ResolveEngine } from "aoa-client-js";',
    'export type { AllowedVerdict, FailErrorVerdict, FailSecurityVerdict, Verdict } from "aoa-client-js";',
  ].join("\n");
}
