# tests/intents/compensate/test_saga_order.py
"""Error processing order tests: compensation is performed BEFORE @on_error.
═══════════════════ ════════════════════ ════════════════════ ════════════════════
STRUCTURE
═══════════════════ ════════════════════ ════════════════════ ════════════════════
TestCompensateBeforeOnError - compensators are executed before @on_error"""
from __future__ import annotations

from unittest.mock import AsyncMock

import pytest

from action_machine.testing import TestBench
from tests.scenarios.domain_model.compensate_actions import (
    CompensateAndOnErrorAction,
    CompensateTestParams,
)
from tests.scenarios.domain_model.compensate_plugins import SagaObserverPlugin
from tests.scenarios.domain_model.services import InventoryService, PaymentService


@pytest.fixture
def saga_observer() -> SagaObserverPlugin:
    """SagaObserverPlugin instance - reset before each test."""
    observer = SagaObserverPlugin()
    observer.reset()
    return observer


@pytest.fixture
def order_bench(
    mock_payment: AsyncMock,
    mock_inventory: AsyncMock,
    saga_observer: SagaObserverPlugin,
) -> TestBench:
    """TestBench with SagaObserverPlugin for CompensateAndOnErrorAction."""
    return TestBench(
        mocks={
            PaymentService: mock_payment,
            InventoryService: mock_inventory,
        },
        plugins=[saga_observer],
        log_coordinator=AsyncMock(),
    )


def get_last_run_events(observer: SagaObserverPlugin) -> list[dict]:
    """Returns events from the last run of the machine."""
    events = observer.collected_events
    last_start = -1
    for i, e in enumerate(events):
        if e["event_type"] == "SagaRollbackStartedEvent":
            last_start = i
    if last_start == -1:
        return events
    return events[last_start:]


class TestCompensateBeforeOnError:
    """Checks that compensators are executed BEFORE @on_error."""

    @pytest.mark.anyio
    async def test_compensators_execute_before_on_error_via_mocks(
        self,
        order_bench: TestBench,
        mock_payment: AsyncMock,
        mock_inventory: AsyncMock,
    ) -> None:
        """Compensators are called BEFORE @on_error: after run() both mocks
        are called and the result is generated by @on_error."""
        # ── Arrange ──
        params = CompensateTestParams(
            user_id="user_order_mock",
            amount=100.0,
            item_id="ITEM-OM1",
            should_fail=True,
        )

        # ── Act ──
        result = await order_bench.run(
            CompensateAndOnErrorAction(),
            params,
            rollup=False,
        )

        # ── Assert ──
        assert mock_payment.refund.call_count >= 1
        assert mock_inventory.unreserve.call_count >= 1
        assert result.status == "handled_after_compensate"
        assert "Finalize error for user_order_mock" in result.detail

    @pytest.mark.anyio
    async def test_compensators_execute_before_on_error_via_events(
        self,
        order_bench: TestBench,
        saga_observer: SagaObserverPlugin,
    ) -> None:
        """The order is confirmed through plugin events: SagaRollbackStartedEvent
        and SagaRollbackCompletedEvent are emitted, and the result is @on_error
        contains status="handled_after_compensate"."""
        # ── Arrange ──
        params = CompensateTestParams(
            user_id="user_order_evt",
            amount=200.0,
            item_id="ITEM-OE1",
            should_fail=True,
        )

        # ── Act ──
        result = await order_bench.run(
            CompensateAndOnErrorAction(),
            params,
            rollup=False,
        )

        # ── Assert ──
        events = get_last_run_events(saga_observer)
        event_types = [e["event_type"] for e in events]

        assert "SagaRollbackStartedEvent" in event_types
        assert "SagaRollbackCompletedEvent" in event_types

        completed = next(e for e in events if e["event_type"] == "SagaRollbackCompletedEvent")
        assert completed["succeeded"] == 2
        assert completed["failed"] == 0

        assert result.status == "handled_after_compensate"
        assert result.status == "handled_after_compensate"
