# scripts/stand_shape_audit.py
"""
Stand shape audit — the "all shapes" enumeration for the demonstrator stand.

═══════════════════════════════════════════════════════════════════════════════
PURPOSE
═══════════════════════════════════════════════════════════════════════════════

"All shapes is true rather than intended" is only checkable against an
enumeration. This script builds the demo coordinator, enumerates the node and
edge kinds the interchange graph publishes for the demo model, marks each kind
``carried & drawn`` or ``named gap``, and rewrites
``specs/004-demonstrator-stand/contracts/shape-coverage.md`` with the result.

═══════════════════════════════════════════════════════════════════════════════
ARCHITECTURE / DATA FLOW
═══════════════════════════════════════════════════════════════════════════════

::

    build_registered_interchange_coordinator()
        |
        v
    get_available_types()  →  node_types / edge_types
        |
        v
    kind in KNOWN_DRAWN?  →  carried & drawn | named gap
        |
        v
    contracts/shape-coverage.md (regenerated)
"""

from __future__ import annotations

import sys
from pathlib import Path

from aoa.demo.model.interchange_demo_coordinator import (
    build_registered_interchange_coordinator,
    import_sample_registration_modules,
)

# Kinds the Maxitor diagrams demonstrably render today (verified by the #201
# recording and the use-case/ERD DuckDB tests). A kind absent from this set is
# written as a named gap — the recorded picture is what upgrades it.
_DRAWN_NODE_KINDS = frozenset(
    {
        "AccessDecide",
        "Action",
        "Application",
        "Domain",
        "Entity",
        "EntityField",
        "Field",
        "Lifecycle",
        "Params",
        "Resource",
        "Result",
        "Role",
        "StateFinal",
        "StateInitial",
        "StateIntermediate",
    }
)

_DRAWN_EDGE_KINDS = frozenset(
    {
        "@access_decide",
        "@check_roles",
        "@compensate",
        "@connection",
        "@depends",
        "@on_error",
        "@regular_aspect",
        "@required_context",
        "@result_checker",
        "@summary_aspect",
        "application",
        "domain",
        "entity_field",
        "entity_relation",
        "entity_schema",
        "entity_specialization",
        "field",
        "generic:params",
        "generic:result",
        "lifecycle",
        "lifecycle_contains_state",
        "lifecycle_transition",
        "parent_action",
        "parent_domain",
        "parent_entity",
        "parent_role",
        "property",
        "sensitive",
    }
)

_OUTPUT = Path("specs/004-demonstrator-stand/contracts/shape-coverage.md")

_PREAMBLE = """# Contract: the "all shapes" enumeration

"All shapes is true rather than intended" is only checkable against an enumeration. This file is
that enumeration, regenerated by `scripts/stand_shape_audit.py` — do not edit the tables by hand.

## Procedure

1. Enumerate the interchange graph's node kinds and edge kinds for the demo model — from
   `NodeGraphCoordinator.get_available_types()`.
2. Mark each kind `carried & drawn` when the Maxitor diagrams demonstrably render it, otherwise
   `named gap` with one line saying what is missing.
3. The recorded picture (issue #202, task T018) upgrades `named gap` rows to `carried & drawn`.
"""


def _table(title: str, kinds: frozenset[str], drawn: frozenset[str]) -> list[str]:
    lines = [f"## {title}", "", "| Kind | Status |", "|------|--------|"]
    for kind in sorted(kinds):
        if kind in drawn:
            lines.append(f"| `{kind}` | carried & drawn |")
        else:
            lines.append(f"| `{kind}` | named gap — not yet confirmed drawn by the recorded picture |")
    lines.append("")
    return lines


def _write_contract(node_kinds: frozenset[str], edge_kinds: frozenset[str]) -> None:
    body = [_PREAMBLE, ""]
    body.extend(_table("Node kinds", node_kinds, _DRAWN_NODE_KINDS))
    body.extend(_table("Edge kinds", edge_kinds, _DRAWN_EDGE_KINDS))
    _OUTPUT.write_text("\n".join(body), encoding="utf-8")


def main() -> int:
    """Build the demo graph, mark every kind, and rewrite the contract table."""
    import_sample_registration_modules()
    coordinator = build_registered_interchange_coordinator()
    available = coordinator.get_available_types()
    node_kinds = available.get("node_types", frozenset())
    edge_kinds = available.get("edge_types", frozenset())
    _write_contract(node_kinds, edge_kinds)
    print(f"shape-coverage.md: {len(node_kinds)} node kinds, {len(edge_kinds)} edge kinds")
    return 0


if __name__ == "__main__":
    sys.exit(main())
